"""
Text and font-related constants
"""

# Fonts
DEFAULT_FONT = "Arial"
DEFAULT_FONT_SIZE = 12
MIN_FONT_SIZE = 6
MAX_FONT_SIZE = 72

# Text Annotation
TEXT_ANNOTATION_WIDTH_PADDING = 10
TEXT_ANNOTATION_HEIGHT_PADDING = 6
TEXT_ANNOTATION_Y_OFFSET = 4
